=== gpetho/albuc_translate/edition_french/chapters.dtd
<!ELEMENT standoffAnnotations (metadata?, chapter+)>
<!ATTLIST standoffAnnotations 
    xmlns:xsi CDATA #REQUIRED
    xsi:noNamespaceSchemaLocation CDATA #REQUIRED
>
<!ELEMENT metadata (sourceFile, dateCreated, createdBy, schemaVersion)>
<!ELEMENT sourceFile EMPTY>
<!ATTLIST sourceFile path CDATA #REQUIRED>
<!ELEMENT dateCreated (#PCDATA)>
<!ELEMENT createdBy (#PCDATA)>
<!ELEMENT schemaVersion (#PCDATA)>

<!ELEMENT chapter (subchapter*)>
<!ATTLIST chapter 
    n CDATA #REQUIRED
    start_s CDATA #REQUIRED
    end_s CDATA #REQUIRED
    id ID #IMPLIED
>

<!ELEMENT subchapter EMPTY>
<!ATTLIST subchapter
    n CDATA #REQUIRED
    start_s CDATA #REQUIRED
    end_s CDATA #REQUIRED
    id ID #IMPLIED
>

=== gpetho/albuc_translate/edition_french/chapters_standoff.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE standoffAnnotations SYSTEM "chapters.dtd">
<standoffAnnotations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:noNamespaceSchemaLocation="chapters.xsd">
    <metadata>
        <sourceFile path="ChirAlbT_text_bfm_mod.xml"/>
        <dateCreated>2024-11-06</dateCreated>
        <createdBy>Gergely Peth≈ë @ALMA</createdBy>
        <schemaVersion>1.0</schemaVersion>
    </metadata>

    <chapter n="Prologue" id="prologue" start_s="s0001" end_s="s0024">
    </chapter>

    <chapter n="1" id="ch1" start_s="s0025" end_s="s0048">
        <subchapter n="1" id="subch1.1" start_s="s0049" end_s="s0057" />
        <subchapter n="2" id="subch1.2" start_s="s0058" end_s="s0061" />
        <subchapter n="3" id="subch1.3" start_s="s0062" end_s="s0069" />
        <subchapter n="4" id="subch1.4" start_s="s0070" end_s="s0072" />
        <subchapter n="5" id="subch1.5" start_s="s0073" end_s="s0075" />
        <subchapter n="6" id="subch1.6" start_s="s0076" end_s="s0079" />
        <subchapter n="7" id="subch1.7" start_s="s0081" end_s="s0081" />
        <subchapter n="8" id="subch1.8" start_s="s0082" end_s="s0084" />
        <subchapter n="9" id="subch1.9" start_s="s0085" end_s="s0086" />
        <subchapter n="10" id="subch1.10" start_s="s0087" end_s="s0090" />
        <subchapter n="11" id="subch1.11" start_s="s0091" end_s="s0095" />
        <subchapter n="12" id="subch1.12" start_s="s0096" end_s="s0099" />
        <subchapter n="13" id="subch1.13" start_s="s0100" end_s="s0101" />
        <subchapter n="14" id="subch1.14" start_s="s0102" end_s="s0104" />
        <subchapter n="15" id="subch1.15" start_s="s0105" end_s="s0107" />
        <subchapter n="16" id="subch1.16" start_s="s0108" end_s="s0120" />
        <subchapter n="17" id="subch1.17" start_s="s0121" end_s="s0131" />
        <subchapter n="18" id="subch1.18" start_s="s0132" end_s="s0135" />
        <subchapter n="19" id="subch1.19" start_s="s0136" end_s="s0137" />
        <subchapter n="20" id="subch1.20" start_s="s0138" end_s="s0140" />
        <subchapter n="21" id="subch1.21" start_s="s0141" end_s="s0146" />
        <subchapter n="22" id="subch1.22" start_s="s0147" end_s="s0149" />
        <subchapter n="23" id="subch1.23" start_s="s0150" end_s="s0151" />
        <subchapter n="24" id="subch1.24" start_s="s0152" end_s="s0156" />
        <subchapter n="25" id="subch1.25" start_s="s0157" end_s="s0164" />
        <subchapter n="26" id="subch1.26" start_s="s0165" end_s="s0168" />
        <subchapter n="27" id="subch1.27" start_s="s0169" end_s="s0170" />
        <subchapter n="28" id="subch1.28" start_s="s0171" end_s="s0174" />
        <subchapter n="29" id="subch1.29" start_s="s0175" end_s="s0178" />
        <subchapter n="30" id="subch1.30" start_s="s0179" end_s="s0183" />
        <subchapter n="31" id="subch1.31" start_s="s0184" end_s="s0188" />
        <subchapter n="32" id="subch1.32" start_s="s0189" end_s="s0192" />
        <subchapter n="33" id="subch1.33" start_s="s0193" end_s="s0195" />
        <subchapter n="34" id="subch1.34" start_s="s0196" end_s="s0198" />
        <subchapter n="35" id="subch1.35" start_s="s0199" end_s="s0200" />
        <subchapter n="36" id="subch1.36" start_s="s0201" end_s="s0205" />
        <subchapter n="37" id="subch1.37" start_s="s0206" end_s="s0207" />
        <subchapter n="38" id="subch1.38" start_s="s0208" end_s="s0209" />
        <subchapter n="39" id="subch1.39" start_s="s0210" end_s="s0211" />
        <subchapter n="40" id="subch1.40" start_s="s0212" end_s="s0214" />
        <subchapter n="41" id="subch1.41" start_s="s0215" end_s="s0242" />
        <subchapter n="42" id="subch1.42" start_s="s0243" end_s="s0245" />
        <subchapter n="43" id="subch1.43" start_s="s0246" end_s="s0250" />
        <subchapter n="44" id="subch1.44" start_s="s0252" end_s="s0258" />
        <subchapter n="45" id="subch1.45" start_s="s0259" end_s="s0270" />
        <subchapter n="46" id="subch1.46" start_s="s0271" end_s="s0273" />
        <subchapter n="47" id="subch1.47" start_s="s0274" end_s="s0280" />
        <subchapter n="48" id="subch1.48" start_s="s0281" end_s="s0282" />
        <subchapter n="49" id="subch1.49" start_s="s0283" end_s="s0284" />
        <subchapter n="50" id="subch1.50" start_s="s0285" end_s="s0287" />
        <subchapter n="51" id="subch1.51" start_s="s0288" end_s="s0293" />
        <subchapter n="52" id="subch1.52" start_s="s0294" end_s="s0300" />
        <subchapter n="53" id="subch1.53" start_s="s0301" end_s="s0308" />
        <subchapter n="54" id="subch1.54" start_s="s0309" end_s="s0310" />
        <subchapter n="55" id="subch1.55" start_s="s0311" end_s="s0314" />
        <subchapter n="56" id="subch1.56" start_s="s0315" end_s="s0321" />
    </chapter>

    <chapter n="2" id="ch2" start_s="s0436" end_s="s0446">
        <subchapter n="1" id="subch2.1" start_s="s0447" end_s="s0456" />
        <subchapter n="2" id="subch2.2" start_s="s0457" end_s="s0462" /> 
        <subchapter n="3" id="subch2.3" start_s="s0463" end_s="s0472" />
        <subchapter n="4" id="subch2.4" start_s="s0473" end_s="s0479" />
        <subchapter n="5" id="subch2.5" start_s="s0480" end_s="s0484" />
        <subchapter n="6" id="subch2.6" start_s="s0485" end_s="s0504" />
        <subchapter n="7" id="subch2.7" start_s="s0505" end_s="s0512" />
        <subchapter n="8" id="subch2.8" start_s="s0513" end_s="s0515" />
        <subchapter n="9" id="subch2.9" start_s="s0516" end_s="s0519" />
        <subchapter n="10" id="subch2.10" start_s="s0520" end_s="s0528" />
        <subchapter n="11" id="subch2.11" start_s="s0529" end_s="s0536" />
        <subchapter n="12" id="subch2.12" start_s="s0537" end_s="s0538" />
        <subchapter n="13" id="subch2.13" start_s="s0539" end_s="s0544" />
        <subchapter n="14" id="subch2.14" start_s="s0545" end_s="s0549" />
        <subchapter n="15" id="subch2.15" start_s="s0550" end_s="s0551" />
        <subchapter n="16" id="subch2.16" start_s="s0552" end_s="s0559" />
        <subchapter n="17" id="subch2.17" start_s="s0560" end_s="s0562" />
        <subchapter n="18" id="subch2.18" start_s="s0563" end_s="s0568" />
        <subchapter n="19" id="subch2.19" start_s="s0569" end_s="s0574" />
        <subchapter n="20" id="subch2.20" start_s="s0575" end_s="s0576" />
        <subchapter n="21" id="subch2.21" start_s="s0577" end_s="s0579" />
        <subchapter n="22" id="subch2.22" start_s="s0580" end_s="s0582" />
        <subchapter n="23" id="subch2.23" start_s="s0583" end_s="s0596" />
        <subchapter n="24" id="subch2.24" start_s="s0597" end_s="s0603" />
        <subchapter n="25" id="subch2.25" start_s="s0604" end_s="s0605" />
        <subchapter n="26" id="subch2.26" start_s="s0606" end_s="s0609" />
        <subchapter n="27" id="subch2.27" start_s="s0610" end_s="s0611" />
        <subchapter n="28" id="subch2.28" start_s="s0612" end_s="s0613" />
        <subchapter n="29" id="subch2.29" start_s="s0614" end_s="s0615" />
        <subchapter n="30" id="subch2.30" start_s="s0616" end_s="s0624" />
        <subchapter n="31" id="subch2.31" start_s="s0625" end_s="s0633" />
        <subchapter n="32" id="subch2.32" start_s="s0634" end_s="s0636" />
        <subchapter n="33" id="subch2.33" start_s="s0637" end_s="s0640" />
        <subchapter n="34" id="subch2.34" start_s="s0641" end_s="s0643" />
        <subchapter n="35" id="subch2.35" start_s="s0644" end_s="s0644" />
        <subchapter n="36" id="subch2.36" start_s="s0645" end_s="s0654" />
        <subchapter n="37" id="subch2.37" start_s="s0655" end_s="s0667" />
        <subchapter n="38" id="subch2.38" start_s="s0668" end_s="s0669" />
        <subchapter n="39" id="subch2.39" start_s="s0670" end_s="s0678" />
        <subchapter n="40" id="subch2.40" start_s="s0679" end_s="s0697" />
        <subchapter n="41" id="subch2.41" start_s="s0698" end_s="s0709" />
        <subchapter n="42" id="subch2.42" start_s="s0710" end_s="s0720" />
        <subchapter n="43" id="subch2.43" start_s="s0721" end_s="s0732" />
        <subchapter n="44" id="subch2.44" start_s="s0733" end_s="s0735" />
        <subchapter n="45" id="subch2.45" start_s="s0736" end_s="s0744" />
        <subchapter n="46" id="subch2.46" start_s="s0745" end_s="s0748" />
        <subchapter n="47" id="subch2.47" start_s="s0749" end_s="s0750" />
        <subchapter n="48" id="subch2.48" start_s="s0751" end_s="s0755" />
        <subchapter n="49" id="subch2.49" start_s="s0756" end_s="s0758" />
        <subchapter n="50" id="subch2.50" start_s="s0759" end_s="s0762" />
        <subchapter n="51" id="subch2.51" start_s="s0763" end_s="s0767" />
        <subchapter n="52" id="subch2.52" start_s="s0768" end_s="s0774" />
        <subchapter n="53" id="subch2.53" start_s="s0775" end_s="s0777" />
        <subchapter n="54" id="subch2.54" start_s="s0778" end_s="s0784" />
        <subchapter n="55" id="subch2.55" start_s="s0785" end_s="s0791" />
        <subchapter n="56" id="subch2.56" start_s="s0792" end_s="s0798" />
        <subchapter n="57" id="subch2.57" start_s="s0799" end_s="s0809" />
        <subchapter n="58" id="subch2.58" start_s="s0810" end_s="s0812" />
        <subchapter n="59" id="subch2.59" start_s="s0813" end_s="s0816" />
        <subchapter n="60" id="subch2.60" start_s="s0817" end_s="s0835" />
        <subchapter n="61" id="subch2.61" start_s="s0836" end_s="s0842" />
        <subchapter n="62" id="subch2.62" start_s="s0843" end_s="s0854" />
        <subchapter n="63" id="subch2.63" start_s="s0855" end_s="s0863" />
        <subchapter n="64" id="subch2.64" start_s="s0864" end_s="s0866" />
        <subchapter n="65" id="subch2.65" start_s="s0867" end_s="s0874" />
        <subchapter n="66" id="subch2.66" start_s="s0875" end_s="s0877" />
        <subchapter n="67" id="subch2.67" start_s="s0878" end_s="s0880" />
        <subchapter n="68" id="subch2.68" start_s="s0881" end_s="s0882" />
